serve:
  cookies:
    same_site_mode: Lax
    # 设置 Cookie 的 SameSite 属性为 Lax 模式，以增强安全性。Lax 模式允许跨站请求时携带 Cookie，但仅限于导航到顶级上下文（例如点击链接）。

urls:
  self:
    issuer: http://127.0.0.1:4444
    # 发行人 URL，用于标识当前的 Hydra 实例
  consent:
    url: http://127.0.0.1:3000/consent
    # 同意页面的 URL，用户在此页面上同意或拒绝 OAuth2 请求
  login:
    url: http://127.0.0.1:3000/login
    # 登录页面的 URL，用户在此页面上进行登录
  registration:
    url: http://127.0.0.1:3000/registration
    # 注册页面的 URL，用户在此页面上进行注册
  logout:
    url: http://127.0.0.1:3000/logout
    # 登出页面的 URL，用户在此页面上进行登出

secrets:
  system:
    - 8KhfJH3kL9mN5pQr2sTv4wXyZ7aC1dEg
    # 系统密钥，用于加密和解密敏感数据。请务必更改此默认值，以确保系统的安全性。

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
      # 支持的主题标识符类型，包括 pairwise（成对标识符）和 public（公开标识符）
    pairwise:
      salt: 8KhfJH3kL9mN5pQr2sTv4wXyZ7aC1dEg
      # 成对标识符的盐值，用于生成唯一的标识符。请务必更改此默认值，以确保生成的标识符的安全性。
